const productos = [
  {
    id: "Aparador-Uspallata",
    titulo: "Aparador Uspallata",
    imagen: "Images/Catalogo/Aparador-Uspallata.png",
    descripcion: "Aparador de seis puertas fabricado en nogal sostenible con tiradores metálicos en acabado latón. Su silueta minimalista realza el veteado natural de la madera, creando una pieza que combina funcionalidad y elegancia atemporal para espacios contemporáneos.",
    Precio: 1000,
    medidas: "180 × 45 × 75 cm",
    materiales: "Nogal macizo FSC®, herrajes de latón",
    acabado: "Aceite natural ecológico",
    peso: "68 kg",
    capacidad: "6 compartimentos interiores",
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: true
  },
  {
    id: "Biblioteca-Recoleta",
    titulo: "Biblioteca Recoleta",
    imagen: "Images/Catalogo/Biblioteca-Recoleta.png",
    descripcion: "Sistema modular de estantes abierto que combina estructura de acero Sage Green y repisas en roble claro. Perfecta para colecciones y objetos de diseño, su diseño versátil se adapta a cualquier espacio contemporáneo con elegancia funcional.",
    Precio: 1000,
    medidas: "100 × 35 × 200 cm",
    materiales: "Estructura de acero, estantes de roble",
    acabado: "Laca mate ecológica",
    peso: "45 kg por estante",
    capacidad: "5 estantes ajustables",
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: true
  },
  {
    id: "Butaca-Mendoza",
    titulo: "Butaca Mendoza",
    imagen: "Images/Catalogo/Butaca-Mendoza.png",
    descripcion: "Butaca tapizada en bouclé Dusty Rose con base de madera de guatambú. El respaldo curvo abraza el cuerpo y ofrece máximo confort, mientras que su diseño orgánico aporta calidez y sofisticación a cualquier ambiente contemporáneo.",
    Precio: 1000,
    medidas: "80 × 75 × 85 cm",
    materiales: "Guatambú macizo, tela bouclé",
    acabado: "Cera vegetal, tapizado premium",
    peso: null,
    capacidad: null,
    tapizado: "Repelente al agua y manchas",
    confort: "Espuma alta densidad",
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: true
  },
  {
    id: "Escritorio-Costa",
    titulo: "Escritorio Costa",
    imagen: "Images/Catalogo/Escritorio-Costa.png",
    descripcion: "Escritorio compacto con cajón organizado y tapa pasacables integrada en bambú laminado. Ideal para espacios de trabajo en casa, combina funcionalidad moderna con estética minimalista y sostenible, perfecto para el trabajo remoto.",
    Precio: 1000,
    medidas: "120 × 60 × 75 cm",
    materiales: "Bambú laminado, herrajes ocultos",
    acabado: "Laca mate resistente",
    peso: null,
    capacidad: null,
    tapizado: null,
    confort: null,
    almacenamiento: "1 cajón con organizador",
    cables: "Pasacables integrado",
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: false
  },
  {
    id: "Mesa-Comedor-Pampa",
    titulo: "Mesa Comedor Pampa",
    imagen: "Images/Catalogo/Mesa-Comedor-Pampa.png",
    descripcion: "Mesa extensible de roble macizo con tablero biselado y sistema de apertura suave. Su diseño robusto y elegante se adapta perfectamente a reuniones íntimas o grandes celebraciones familiares, extendiéndose de 6 a 10 comensales.",
    Precio: 1000,
    medidas: "160-240 × 90 × 75 cm",
    materiales: "Roble macizo FSC®, mecanismo alemán",
    acabado: "Aceite-cera natural",
    peso: null,
    capacidad: "6-10 comensales",
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: "Sistema de mariposa central",
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: false
  },
  {
    id: "Mesa-de-Centro-Araucaria",
    titulo: "Mesa de Centro Araucaria",
    imagen: "Images/Catalogo/Mesa-de-Centro-Araucaria.png",
    descripcion: "Mesa de centro con sobre circular de mármol Patagonia y base de tres patas en madera de nogal. Su diseño minimalista se convierte en el punto focal perfecto para cualquier sala de estar contemporánea, combinando la frialdad del mármol con la calidez de la madera.",
    Precio: 1000,
    medidas: "90 × 90 × 45 cm",
    materiales: "Sobre de mármol Patagonia, patas de nogal",
    acabado: "Mármol pulido, aceite natural en madera",
    peso: "42 kg",
    capacidad: null,
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: "25 kg distribuidos",
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: false
  },
  {
    id: "Mesa-de-Noche-Aconcagua",
    titulo: "Mesa de Noche Aconcagua",
    imagen: "Images/Catalogo/Mesa-de-Noche-Aconcagua.png",
    descripcion: "Mesa de noche con cajón oculto y repisa inferior en roble certificado FSC®. Su diseño limpio y funcional permite convivir con diferentes estilos de dormitorio, ofreciendo almacenamiento discreto y elegante para objetos personales.",
    Precio: 1000,
    medidas: "45 × 35 × 60 cm",
    materiales: "Roble macizo FSC®, herrajes soft-close",
    acabado: "Barniz mate de poliuretano",
    peso: null,
    capacidad: null,
    tapizado: null,
    confort: null,
    almacenamiento: "1 cajón + repisa inferior",
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: "Cajón con cierre suave",
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: false
  },
  {
    id: "Silla-de-Trabajo-Belgrano",
    titulo: "Silla de Trabajo Belgrano",
    imagen: "Images/Catalogo/Silla-de-Trabajo-Belgrano.png",
    descripcion: "Silla ergonómica regulable en altura con respaldo de malla transpirable y asiento tapizado en tejido reciclado. Diseñada para largas jornadas de trabajo con máximo confort y apoyo lumbar, ideal para oficinas en casa y espacios de coworking.",
    Precio: 1000,
    medidas: "60 × 60 × 90-100 cm",
    materiales: "Malla técnica, tejido reciclado",
    acabado: "Base cromada, tapizado premium",
    peso: null,
    capacidad: null,
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: "Altura + inclinación respaldo",
    certificacion: "Ergonomía europea EN 1335",
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: false
  },
  {
    id: "Sillas-Córdoba",
    titulo: "Sillas Córdoba",
    imagen: "Images/Catalogo/Sillas-Córdoba.png",
    descripcion: "Set de cuatro sillas apilables en contrachapado moldeado de nogal y estructura tubular pintada en Sage Green. Su diseño ergonómico y materiales de calidad garantizan comodidad y durabilidad en el uso diario, perfectas para comedores contemporáneos.",
    Precio: 1000,
    medidas: "45 × 52 × 80 cm (cada una)",
    materiales: "Contrachapado nogal, tubo de acero",
    acabado: "Laca mate, pintura epoxi",
    peso: null,
    capacidad: null,
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: "Hasta 6 sillas",
    incluye: "Set de 4 sillas",
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: false
  },
  {
    id: "Sillón-Copacabana",
    titulo: "Sillón Copacabana",
    imagen: "Images/Catalogo/Sillón-Copacabana.png",
    descripcion: "Sillón lounge en cuero cognac con base giratoria en acero Burnt Sienna. Inspirado en la estética brasilera moderna de los 60, combina comodidad excepcional con un diseño icónico que trasciende tendencias y épocas.",
    Precio: 1000,
    medidas: "90 × 85 × 95 cm",
    materiales: "Cuero curtido vegetal, acero pintado",
    acabado: "Cuero anilina premium",
    peso: null,
    capacidad: null,
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: "360° silenciosa y suave",
    garantia: "10 años en estructura",
    estructura: null,
    sostenibilidad: null,
    colchon: null,
    masVendidos: false
  },
  {
    id: "Sofá-Patagonia",
    titulo: "Sofá Patagonia",
    imagen: "Images/Catalogo/Sofá-Patagonia.png",
    descripcion: "Sofá de tres cuerpos tapizado en lino Warm Alabaster con patas cónicas de madera. Los cojines combinan espuma de alta resiliencia con plumón reciclado, ofreciendo comodidad duradera y sostenible para el hogar moderno.",
    Precio: 1000,
    medidas: "220 × 90 × 80 cm",
    materiales: null,
    acabado: null,
    peso: null,
    capacidad: null,
    tapizado: "Lino 100% natural premium",
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: null,
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: "Madera de eucalipto certificada FSC®",
    sostenibilidad: "Materiales 100% reciclables",
    colchon: null,
    masVendidos: false
  },
  {
    id: "Cama-Neuquen",
    titulo: "Cama Neuquén",
    imagen: "Images/Catalogo/Cama-Neuquén.png",
    descripcion: "Cama plataforma con cabecero flotante tapizado en lino natural y estructura de madera maciza. Su diseño minimalista y sofisticado crea un ambiente de serenidad y elegancia, perfecto para dormitorios contemporáneos que buscan paz y simplicidad.",
    Precio: 1000,
    medidas: "160 × 200 × 90 cm",
    materiales: "Roble macizo FSC®, tapizado lino",
    acabado: "Aceite natural, tapizado premium",
    peso: null,
    capacidad: null,
    tapizado: null,
    confort: null,
    almacenamiento: null,
    cables: null,
    extension: null,
    carga_max: null,
    caracteristicas: "Cabecero flotante acolchado",
    regulacion: null,
    certificacion: null,
    apilables: null,
    incluye: null,
    rotacion: null,
    garantia: null,
    estructura: null,
    sostenibilidad: null,
    colchon: "Compatible con colchón 160×200",
    masVendidos: false
  }
];